import "server-only";

import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getPublicEventBySlug, getPublicEventsByCategory, toPublicEventDetail, toPublicEventSummary } from "@/lib/events/public-events";
import { milestoneOneEvents } from "@/lib/events/sample-events";
import { mapPublicEventCardRow, type PublicEventCardRow } from "@/server/queries/public-event-mappers";
import type { PublicEventDetail } from "@/types/events";

function hasSupabaseConfig() { return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY); }
function sampleFeatured() { const openForApplication = getPublicEventsByCategory(milestoneOneEvents).filter((event) => event.applicationDeadline && new Date(event.applicationDeadline).getTime() > Date.now()); const upcoming = getPublicEventsByCategory(milestoneOneEvents).filter((event) => !openForApplication.some((openEvent) => openEvent.slug === event.slug)); return { openForApplication, upcoming }; }
export async function listPublicEventCards(categorySlug?: string) { if (!hasSupabaseConfig()) return getPublicEventsByCategory(milestoneOneEvents, categorySlug); const supabase = await createSupabaseServerClient(); let query = supabase.from("public_event_cards").select("id, slug, title, category_name, category_slug, tags, summary, cover_image_url, starts_at, ends_at, timezone, city, district, application_deadline, waitlist_enabled, host_display_name, host_background_title, host_bio, seat_count, confirmed_seat_count").order("starts_at", { ascending: true }); if (categorySlug) query = query.eq("category_slug", categorySlug); const { data, error } = await query; return error || !data ? getPublicEventsByCategory(milestoneOneEvents, categorySlug) : data.map((row) => mapPublicEventCardRow(row as PublicEventCardRow)); }
export async function getFeaturedPublicEventCards() { const cards = await listPublicEventCards(); const openForApplication = cards.filter((event) => event.applicationDeadline && new Date(event.applicationDeadline).getTime() > Date.now()); const upcoming = cards.filter((event) => !openForApplication.some((openEvent) => openEvent.slug === event.slug)); return hasSupabaseConfig() ? { openForApplication, upcoming } : sampleFeatured(); }
export async function getPublicEventDetail(slug: string): Promise<PublicEventDetail | null> { if (!hasSupabaseConfig()) return getPublicEventBySlug(milestoneOneEvents, slug); const sampleEvent = milestoneOneEvents.find((event) => event.slug === slug); if (sampleEvent) return toPublicEventDetail(sampleEvent); const card = (await listPublicEventCards()).find((event) => event.slug === slug); if (!card) return null; return { ...card, description: card.summary, discussionDirection: "更多交流方向將由主辦人於活動頁更新。", topicPrompts: [], suitableFor: "對本場主題有興趣，並願意在六人小聚中自然交流的人。", feeNote: "活動本身不收費，僅需負擔自己的餐飲費用。", seats: Array.from({ length: 6 }, (_, index) => ({ seatNumber: index + 1, seatType: index === 0 ? "host" : "reserved", seatStatus: index === 0 ? "confirmed" : "reserved", displayLabel: index === 0 ? "主辦人" : "保留席" })) }; }
export function samplePublicEventSummaryBySlug(slug: string) { const event = milestoneOneEvents.find((item) => item.slug === slug); return event ? toPublicEventSummary(event) : null; }
