import type { EventRecord, PublicEventDetail, PublicEventSummary } from "@/types/events";

const isPublished = (event: EventRecord) => event.publicationStatus === "published" && event.lifecycleStatus === "scheduled";
const hasOpenApplications = (event: EventRecord) => Boolean(event.applicationDeadline && new Date(event.applicationDeadline).getTime() > Date.now());
const sortByStartTime = <T extends { startsAt: string }>(events: T[]) => [...events].sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());

export function toPublicEventSummary(event: EventRecord): PublicEventSummary { return { slug: event.slug, title: event.title, categoryName: event.category.name, categorySlug: event.category.slug, tags: event.tags, summary: event.summary, coverImageUrl: event.coverImageUrl, startsAt: event.startsAt, endsAt: event.endsAt, city: event.city, district: event.district, applicationDeadline: event.applicationDeadline, waitlistEnabled: event.waitlistEnabled, seatCount: event.seats.length, confirmedSeatCount: event.seats.filter((seat) => seat.seatStatus === "confirmed").length, host: event.host }; }
export function toPublicEventDetail(event: EventRecord): PublicEventDetail { return { ...toPublicEventSummary(event), description: event.description, discussionDirection: event.discussionDirection, topicPrompts: event.topicPrompts, suitableFor: event.suitableFor, feeNote: event.feeNote, minimumSpendNote: event.minimumSpendNote, publicNotes: event.publicNotes, seats: event.seats.map((seat) => ({ ...seat, participant: seat.participant?.visibility === "hidden" ? { visibility: "hidden" } : seat.participant })) }; }
export function getFeaturedPublicEvents(events: EventRecord[]) { const published = sortByStartTime(events.filter(isPublished)).map(toPublicEventSummary); return { openForApplication: published.filter((event) => Boolean(event.applicationDeadline && new Date(event.applicationDeadline).getTime() > Date.now())), upcoming: published.filter((event) => !event.applicationDeadline || new Date(event.applicationDeadline).getTime() <= Date.now()) }; }
export function getPublicEventBySlug(events: EventRecord[], slug: string) { const event = events.find((item) => item.slug === slug); return event && isPublished(event) ? toPublicEventDetail(event) : null; }
export function getPublicEventsByCategory(events: EventRecord[], categorySlug?: string) { return sortByStartTime(events.filter(isPublished)).filter((event) => !categorySlug || event.category.slug === categorySlug).map(toPublicEventSummary); }
export { hasOpenApplications };
