import type { EventRecord } from "@/types/events";

const now = new Date("2026-07-23T07:00:00.000Z");
const inDays = (days: number) =>
  new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const milestoneOneEvents: EventRecord[] = [
  {
    id: "evt_game_creators",
    slug: "game-creators-taipei-summer",
    title: "獨立遊戲創作者午後聚",
    category: { name: "數位遊戲", slug: "digital-games" },
    tags: ["獨立遊戲", "企劃", "發行"],
    summary: "給正在做遊戲、準備發表作品，或想交流開發節奏的創作者。",
    description:
      "這場聚會從獨立遊戲的製作日常開始聊起，包含題材選擇、製作節奏、展會準備與發行前後的現實問題。",
    discussionDirection:
      "聚焦小團隊如何在有限時間裡推進作品，也歡迎分享工具、社群經營與 demo 測試經驗。",
    topicPrompts: [
      "目前卡住的一個開發問題",
      "最近一次收到有幫助的玩家回饋",
      "希望認識哪一類創作者",
    ],
    suitableFor: "獨立遊戲開發者、企劃、美術、音樂、發行與社群經營者。",
    feeNote: "活動本身不收費，僅需負擔自己的餐飲費用。",
    minimumSpendNote: "低消一杯飲品。",
    publicNotes: "不需要準備簡報，帶著作品截圖或 demo 也可以。",
    coverImageUrl: "/assets/brand/logo.svg",
    startsAt: inDays(21),
    endsAt: inDays(21.125),
    timezone: "Asia/Taipei",
    city: "台北市",
    district: "大安區",
    applicationOpensAt: inDays(-2),
    applicationDeadline: inDays(10),
    waitlistEnabled: true,
    publicationStatus: "published",
    lifecycleStatus: "scheduled",
    host: {
      displayName: "Ian",
      backgroundTitle: "遊戲與內容策展",
      bio: "長期關注台灣獨立遊戲、展會與內容企劃，希望把散落的經驗放在同一張桌上聊。",
    },
    seats: [
      {
        seatNumber: 1,
        seatType: "host",
        seatStatus: "confirmed",
        displayLabel: "主辦人",
        participant: {
          visibility: "profile",
          displayName: "Ian",
          backgroundTitle: "遊戲與內容策展",
          bio: "朋友加一主辦人。",
        },
      },
      {
        seatNumber: 2,
        seatType: "direct_invite",
        seatStatus: "confirmed",
        displayLabel: "指定邀請",
        participant: {
          visibility: "background_only",
          backgroundTitle: "獨立遊戲製作人",
        },
      },
      {
        seatNumber: 3,
        seatType: "public_application",
        seatStatus: "open",
        displayLabel: "公開申請",
      },
      {
        seatNumber: 4,
        seatType: "public_application",
        seatStatus: "open",
        displayLabel: "公開申請",
      },
      {
        seatNumber: 5,
        seatType: "reserved",
        seatStatus: "reserved",
        displayLabel: "保留席",
      },
      {
        seatNumber: 6,
        seatType: "plus_one",
        seatStatus: "open",
        displayLabel: "加一同行",
      },
    ],
    privateVenue: {
      name: "測試咖啡廳",
      address: "台北市大安區完整地址 1 號",
      meetingInstructions: "請到二樓包廂。",
      contact: "0900-000-000",
    },
  },
  {
    id: "evt_vtuber",
    slug: "vtuber-production-chat",
    title: "VTuber 企劃與製作交流",
    category: { name: "VTuber", slug: "vtuber" },
    tags: ["VTuber", "內容製作"],
    summary: "聊聊 VTuber 內容製作、直播企劃與合作節奏。",
    description: "以企劃、營運與製作協作為主題，交換實際執行經驗。",
    discussionDirection: "從企劃到上線的流程與取捨。",
    topicPrompts: ["最近一次企劃復盤", "直播與短影音的分工", "合作時最需要先講清楚的事"],
    suitableFor: "VTuber、企劃、剪輯、繪師、營運與相關製作者。",
    feeNote: "活動本身不收費，僅需負擔自己的餐飲費用。",
    coverImageUrl: "/assets/brand/logo.svg",
    startsAt: inDays(35),
    endsAt: inDays(35.125),
    timezone: "Asia/Taipei",
    city: "新北市",
    district: "板橋區",
    waitlistEnabled: false,
    publicationStatus: "published",
    lifecycleStatus: "scheduled",
    host: {
      displayName: "Mika",
      backgroundTitle: "直播內容製作",
      bio: "熟悉直播節目規劃與跨職能合作。",
    },
    seats: [
      { seatNumber: 1, seatType: "host", seatStatus: "confirmed", displayLabel: "主辦人" },
      {
        seatNumber: 2,
        seatType: "direct_invite",
        seatStatus: "invitation_pending",
        displayLabel: "邀請席",
      },
      {
        seatNumber: 3,
        seatType: "public_application",
        seatStatus: "open",
        displayLabel: "公開申請",
      },
      {
        seatNumber: 4,
        seatType: "reserved",
        seatStatus: "reserved",
        displayLabel: "保留席",
      },
      {
        seatNumber: 5,
        seatType: "reserved",
        seatStatus: "reserved",
        displayLabel: "保留席",
      },
      {
        seatNumber: 6,
        seatType: "reserved",
        seatStatus: "reserved",
        displayLabel: "保留席",
      },
    ],
    privateVenue: {
      name: "私人場地",
      address: "不應公開的完整地址",
      meetingInstructions: "不應公開的集合方式",
      contact: "0900-111-111",
    },
  },
  {
    id: "evt_draft",
    slug: "private-draft",
    title: "未公開草稿",
    category: { name: "其他", slug: "other" },
    tags: [],
    summary: "這筆資料不可出現在公開頁。",
    description: "草稿活動。",
    discussionDirection: "草稿。",
    topicPrompts: [],
    suitableFor: "草稿。",
    feeNote: "活動本身不收費。",
    coverImageUrl: "/assets/brand/logo.svg",
    startsAt: inDays(14),
    endsAt: inDays(14.125),
    timezone: "Asia/Taipei",
    city: "台北市",
    district: "中山區",
    waitlistEnabled: false,
    publicationStatus: "draft",
    lifecycleStatus: "scheduled",
    host: {
      displayName: "Draft Host",
      backgroundTitle: "測試",
      bio: "測試。",
    },
    seats: [],
    privateVenue: {
      name: "不公開咖啡廳",
      address: "不公開完整地址",
      meetingInstructions: "不公開集合方式",
      contact: "0900-222-222",
    },
  },
  {
    id: "evt_past",
    slug: "past-publishing",
    title: "出版與內容過往聚",
    category: { name: "出版與內容", slug: "publishing-content" },
    tags: ["出版", "內容"],
    summary: "過往活動不顯示於首頁。",
    description: "過往活動。",
    discussionDirection: "過往。",
    topicPrompts: [],
    suitableFor: "內容工作者。",
    feeNote: "活動本身不收費。",
    coverImageUrl: "/assets/brand/logo.svg",
    startsAt: inDays(-10),
    endsAt: inDays(-9.875),
    timezone: "Asia/Taipei",
    city: "台中市",
    district: "西區",
    waitlistEnabled: false,
    publicationStatus: "published",
    lifecycleStatus: "completed",
    host: {
      displayName: "Yun",
      backgroundTitle: "內容編輯",
      bio: "內容與出版工作者。",
    },
    seats: [],
    privateVenue: {
      name: "不公開咖啡廳",
      address: "不公開完整地址",
      meetingInstructions: "不公開集合方式",
      contact: "0900-333-333",
    },
  },
];
