"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { withdrawApplication, type ApplicationStatus } from "@/server/domain/applications";
const applicationSchema = z.object({ eventId: z.string().min(1), eventSlug: z.string().min(1), eventHostUserId: z.string().min(1), applicantUserId: z.string().min(1), motivation: z.string().min(10, "請簡短說明想參加的原因。"), discussionInterest: z.string().optional() });
export async function submitApplication(formData: FormData) { const parsed = applicationSchema.safeParse({ eventId: formData.get("eventId"), eventSlug: formData.get("eventSlug"), eventHostUserId: formData.get("eventHostUserId"), applicantUserId: formData.get("applicantUserId"), motivation: formData.get("motivation"), discussionInterest: formData.get("discussionInterest") || undefined }); if (!parsed.success) redirect(`/events/${formData.get("eventSlug")}?application=invalid`); const supabase = await createSupabaseServerClient(); const { error } = await supabase.rpc("submit_application", { event_uuid: parsed.data.eventId, motivation_text: parsed.data.motivation, discussion_interest_text: parsed.data.discussionInterest ?? null, plus_one: false, visibility: "profile" }); if (error) redirect(`/events/${parsed.data.eventSlug}?application=failed`); revalidatePath("/me/applications"); redirect("/me/applications?status=submitted"); }
export async function withdrawApplicationAction(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); const status = String(formData.get("status") ?? "submitted"); withdrawApplication({ status: status as ApplicationStatus }); const supabase = await createSupabaseServerClient(); await supabase.rpc("withdraw_application", { application_uuid: applicationId }); revalidatePath("/me/applications"); }
export async function confirmApplicationAction(formData: FormData) { const supabase = await createSupabaseServerClient(); await supabase.rpc("confirm_accepted_application", { application_uuid: String(formData.get("applicationId") ?? "") }); revalidatePath("/me/events"); }
